spring:
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    flyway.locations.filsystem: db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
    defer-datasource-initialization: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum
    username: postgres
    password: danilo
  #h2:
   # console:
    #  enabled: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 58efbdbacdf9b8
    password: 63315f70ae0f23
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: secreto