spring:
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    flyway.locations.filsystem: db/migration
  jpa:
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
jwt:
  secret: secreto
