name: CD

on:
  push:
    branches: 
     - "master"
#o que será executado de fato na pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
            heroku_api_key: ${{secrets.FORUM_API_ENV}}
            heroku_app_name: ${{secrets.FORUM_APP_NAME}}
            heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache de dependencias
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{hashFiles('**/build.gradle.kts')}}
          restore-keys: ${{ runner.os }}-m2

      - name: Run gradle clean
        run: gradle clean

      - name: Run gradle package
        run: gradle assemble
        
      - name: Update heroku
        run: heroku update
        
      - name: Login container registry
        env:
          FORUM_API_ENV: ${{ secrets.FORUM_API_ENV }}
        run: docker login --username=${{secrets.HEROKU_EMAIL}} --password=$(heroku auth:token) registry.heroku.com
        #run: heroku login
        
      - name: Push container registry
        env:
          FORUM_API_ENV: ${{ secrets.FORUM_API_ENV }}
        run: heroku container:push -a ${{ secrets.FORUM_APP_NAME }} web

      - name: Release container registry
        env:
          FORUM_API_ENV: ${{ secrets.FORUM_API_ENV }}
        run: heroku container:release -a ${{ secrets.FORUM_APP_NAME }} web

#ENV E NOME DA APLICACAO API KEY CRIPTOGRAFADA EM SECRETs em Actions
#NO REPO GITHUB > SETTINGS > SECRETS > New repository secret
